### ISSUE TITLE
hmms clusters vs clusters_merged

### ISSUE THREAD

**Issue by jerryyhe** [ParkinsonLab/eps_biofilms#1]
Hello, 

I'm wondering what the difference between the clusters and clusters_merged HMMs for each EPS operon are? Are one set of HMMs the original HMM and the other set the iterated version?

**Comment by cedatorma** [comment]
Hello @jerryyhe,

The hmm models in the ./clusters/ directory are sets of predicted EPS operon subunit sequences that were assigned to the same 'evolutionary lineage' from phylogenetic clustering. These would be akin to orthologous grouping and they can be used to provide a more refined level of annotation to distinguish loci which have come from a different phylogenetic background, or have arisen due to duplication, truncation, or HGT.

The hmm models in the ./clusters_merged/ directory are generated from all of those putative EPS operon subunit sequences combined and can be used to generally identify putative gene families which are found associated with EPS operon machinery.

**Comment by jerryyhe** [comment]
Amazing, thanks for the response Cedoljub - this pipeline looks like it'll be really useful for me!
